const allUsuarios = [
  {
    legajo: 'A',
    name: 'Usuario',
    turno: 'A',
    password: 'noPass',
  },
  {
    legajo: 'B',
    name: 'Usuario',
    turno: 'B',
    password: 'noPass',
  },
  {
    legajo: 'C',
    name: 'Usuario',
    turno: 'C',
    password: 'noPass',
  },
  {
    legajo: 'D',
    name: 'Usuario',
    turno: 'D',
    password: 'noPass',
  },
  {
    legajo: 2105,
    name: 'Claudio Suarez',
    turno: 'A',
    password: '123',
  },
  {
    legajo: 739,
    name: 'Fernan Colazo',
    turno: 'A',
    password: '123',
  },
  {
    legajo: 2688,
    name: 'Cristian Bartolucci',
    turno: 'A',
    password: '123',
  },
  {
    legajo: 2739,
    name: 'Bruno Carassai',
    turno: 'A',
    password: '123',
  },
  {
    legajo: 2740,
    name: 'Matias Gallafent',
    turno: 'A',
    password: '123',
  },
  {
    legajo: 2649,
    name: 'Cecilia Ramallo',
    turno: 'A',
    password: '123',
  },
  {
    legajo: 2653,
    name: 'Patricia Marazzi',
    turno: 'B',
    password: '123',
  },
  {
    legajo: 2475,
    name: 'Alejandra Caminos',
    turno: 'B',
    password: '123',
  },
  {
    legajo: 2570,
    name: 'Fernando Leon',
    turno: 'B',
    password: '123',
  },
  {
    legajo: 2693,
    name: 'Facundo Ribles',
    turno: 'B',
    password: '123',
  },
  {
    legajo: 2692,
    name: 'Roman Tacconi',
    turno: 'B',
    password: '123',
  },
  {
    legajo: 2695,
    name: 'Emanuel Gonzalez',
    turno: 'B',
    password: '123',
  },
  {
    legajo: 2697,
    name: 'Gustavo Tiseira',
    turno: 'C',
    password: 31233722424,
  },
  {
    legajo: 2694,
    name: 'Hernan Romero',
    turno: 'C',
    password: '123',
  },
  {
    legajo: 2285,
    name: 'Laura Gonzalez',
    turno: 'C',
    password: '123',
  },
  {
    legajo: 2704,
    name: 'Dalma Roldan',
    turno: 'C',
    password: '123',
  },
  {
    legajo: 2589,
    name: 'Sandra Chaparro',
    turno: 'C',
    password: '123',
  },
  {
    legajo: 2589,
    name: 'Maria Encina',
    turno: 'C',
    password: '123',
  },
  {
    legajo: 2595,
    name: 'Mariana Perez',
    turno: 'C',
    password: '123',
  },
  {
    legajo: 2691,
    name: 'Javier Carcar',
    turno: 'D',
    password: '123',
  },
  {
    legajo: 2737,
    name: 'Angel Zapata',
    turno: 'D',
    password: '123',
  },
  {
    legajo: 2591,
    name: 'Mariana Diaz',
    turno: 'D',
    password: '123',
  },
  {
    legajo: 1544,
    name: 'Claudia Cabrera',
    turno: 'D',
    password: '123',
  },
  {
    legajo: 2563,
    name: 'Soledad Tisera',
    turno: 'D',
    password: '123',
  },
]

module.exports = {
  allUsuarios,
}
